In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [2]:
x.dtype

dtype('int64')

In [3]:
y = np.array([[True, False],[True, True]])
y

array([[ True, False],
       [ True,  True]], dtype=bool)

In [4]:
y.dtype

dtype('bool')

In [5]:
y.shape

(2, 2)

In [6]:
z = np.array([x,y])
z

array([array([1, 2, 3]),
       array([[ True, False],
       [ True,  True]], dtype=bool)], dtype=object)

### You'll want to avoid object dtypes. It's typically slow.

In [7]:
x = np.arange(5)
print 'x =', x
print 'x has the size of', x.shape
print 'x + 1 = ', x + 1, ' Note: If x was a python list this would produce an error!!!'

x = [0 1 2 3 4]
x has the size of (5,)
x + 1 =  [1 2 3 4 5]  Note: If x was a python list this would produce an error!!!


In [8]:
y = np.array([10 * np.arange(5), 5 * np.arange(5)])
print 'y =', y, '\n'
print 'y has the size of', y.shape, '\n'
print 'y + 1 = ', y + 1, ' Note: If y was a python list this would produce an error!!!'

y = [[ 0 10 20 30 40]
 [ 0  5 10 15 20]] 

y has the size of (2, 5) 

y + 1 =  [[ 1 11 21 31 41]
 [ 1  6 11 16 21]]  Note: If y was a python list this would produce an error!!!


In [9]:
x * y

array([[  0,  10,  40,  90, 160],
       [  0,   5,  20,  45,  80]])

### The DataFrame

In [10]:
np.random.seed(42)
# putting data in as a dict {'column name':column values}
df = pd.DataFrame({'A': [1, 2, 3], 'B': [True, True, False],  'C': np.random.randn(3)}, index=['a', 'b', 'c'])
df

A      B         C
a  1   True  0.496714
b  2   True -0.138264
c  3  False  0.647689

### Access by columns

In [11]:
df['A']

a    1
b    2
c    3
Name: A, dtype: int64

In [12]:
wantedColumns = ['A', 'C']
df[wantedColumns]

A         C
a  1  0.496714
b  2 -0.138264
c  3  0.647689

### Access by rows

In [13]:
df.loc['a']

A            1
B         True
C    0.4967142
Name: a, dtype: object

In [14]:
df.loc[['a','c']]

A      B         C
a  1   True  0.496714
c  3  False  0.647689

In [15]:
df.loc['a':'c']

A      B         C
a  1   True  0.496714
b  2   True -0.138264
c  3  False  0.647689

In [16]:
df.iloc[[1,2]]

A      B         C
b  2   True -0.138264
c  3  False  0.647689

In [17]:
print df.loc['b','C']
print df.iloc[1,2]

-0.138264301171
-0.138264301171


In [18]:
df.loc['c']

A            3
B        False
C    0.6476885
Name: c, dtype: object

## Summary
* Use [ ] for selecting columns
* Use .loc[row_lables, column_labels] for label-based indexing
* Use .iloc[row_positions, column_positions] for positional index

In [19]:
df.loc['a':'c']

A      B         C
a  1   True  0.496714
b  2   True -0.138264
c  3  False  0.647689

In [20]:
myFriendsdf = pd.DataFrame({'Iran': [1, 0, 0], 'Turkey':[0, 1, 0], 'Portugal': [0, 0, 1]}
                          , index=['Arash', 'Nariman', 'Siavash'])
myFriendsdf

Iran  Portugal  Turkey
Arash       1         0       0
Nariman     0         0       1
Siavash     0         1       0

In [21]:
myFriendsdf['Iran']
myFriendsdf.loc['Nariman', 'Turkey']
myFriendsdf.iloc[1,2]
myFriendsdf.loc['Nariman':'Siavash', 'Portugal':'Turkey']

Portugal  Turkey
Nariman         0       1
Siavash         1       0

In [22]:
myFriendsdf.index

Index([u'Arash', u'Nariman', u'Siavash'], dtype='object')

In [23]:
myFriendsdf.columns

Index([u'Iran', u'Portugal', u'Turkey'], dtype='object')